services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    depends_on:
      - keeper
    restart: unless-stopped

  firehose:
    image: ${IMAGE_NAME}:${APP_VERSION}-firehose
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONASYNCIODEBUG=1
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    depends_on:
      - clickhouse
    volumes:
      - ./cursor.txt:/app/cursor.txt
    restart: unless-stopped

  keeper:
    image: clickhouse/clickhouse-keeper:latest
    ports:
      - "9181:9181"
      - "9444:9444"
    volumes:
      - keeper_data:/var/lib/clickhouse-keeper
      - ./docker/keeper.d:/etc/clickhouse-keeper
    restart: unless-stopped

  webapp:
    image: ${IMAGE_NAME}:${APP_VERSION}-webapp
    build:
      context: .
      dockerfile: webapp.Dockerfile
    expose:
      - "8000"
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
    depends_on:
      - clickhouse
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./bluehoover/dashboard/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - webapp
    restart: unless-stopped

volumes:
  keeper_data:
  clickhouse_data:
